<?php

namespace App\Filament\Resources;

use App\Filament\Resources\ContactMethodResource\Pages;
use App\Filament\Resources\ContactMethodResource\RelationManagers;
use App\Models\ContactMethod;
use Filament\Forms;
use Filament\Resources\Form;
use Filament\Resources\Resource;
use Filament\Resources\Table;
use Filament\Tables;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\FileUpload;
use Illuminate\Support\Str;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Columns\ImageColumn;
use Filament\Tables\Columns\SelectColumn;
use Illuminate\Support\Facades\DB;
use App\Models\CompanyName;

class ContactMethodResource extends Resource
{
    protected static ?string $model = ContactMethod::class;

    protected static ?string $navigationIcon = 'heroicon-o-collection';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('name')
                    ->required()
                    ->reactive()
                    ->afterStateUpdated(function (\Closure $set, $state) {
                        $set('slug', Str::slug($state));
                    }),
                Forms\Components\TextInput::make('slug')->required(),

                TextInput::make('description')
                    ->label(__(
                        'description'))
                    ->nullable(),
                TextInput::make('meta_title')
                    ->label(__(
                        'Meta Title'))
                    ->nullable(),

                TextInput::make('meta_description')
                    ->label(__('Meta Description'))
                    ->nullable(),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('name')->label(__('Platform Name'))->searchable()->sortable(),
                TextColumn::make('meta_title')->label(__('Meta Title'))->searchable()->sortable(),
                TextColumn::make('meta_description')->label(__('Meta Description'))->searchable()->sortable(),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\DeleteBulkAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListContactMethods::route('/'),
            'create' => Pages\CreateContactMethod::route('/create'),
            'edit' => Pages\EditContactMethod::route('/{record}/edit'),
        ];
    }

    protected static function getNavigationGroup(): ?string
    {
        return __('Settings');
    }

    public static function getLabel(): ?string
    {
        return __('Contact Method  ');
    }

    public static function getPluralLabel(): ?string
    {
        return __('Contact Methods   ');
    }
    protected static function getNavigationBadge(): ?string
    {
        return self::getModel()::count(); // TODO: Change the autogenerated stub
    }
}
