<?php

namespace App\Filament\Resources;

use App\Filament\Resources\FinancialAssetResource\Pages;
use App\Filament\Resources\FinancialAssetResource\RelationManagers;
use App\Models\FinancialAsset;
use Filament\Forms;
use Filament\Resources\Form;
use Filament\Resources\Resource;
use Filament\Resources\Table;
use Filament\Tables;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use Filament\Tables\Columns\TextColumn;
use Filament\Forms\Components\TextInput;

class FinancialAssetResource extends Resource
{
    protected static ?string $model = FinancialAsset::class;

    protected static ?string $navigationIcon = 'heroicon-o-collection';

    public static function form(Form $form): Form
    {
        return $form
        ->schema([
            TextInput::make('name')
            ->label(__('Platform Name'))

            ->required(),

            TextInput::make('meta_title')
            ->label(__('Meta Title'))
            ->nullable(),
        TextInput::make('meta_description')
            ->label(__('Meta Description'))
            ->nullable(),
        ]);
}

public static function table(Table $table): Table
{
    return $table
        ->columns([
            TextColumn::make('name')->label(__('Platform Name'))->searchable()->sortable(),
            TextColumn::make('meta_title')->label(__('Meta Title'))->searchable()->sortable(),
            TextColumn::make('meta_description')->label(__('Meta Description'))->searchable()->sortable(),
        ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\DeleteBulkAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListFinancialAssets::route('/'),
            'create' => Pages\CreateFinancialAsset::route('/create'),
            'edit' => Pages\EditFinancialAsset::route('/{record}/edit'),
        ];
    }



    protected static function getNavigationGroup(): ?string
    {
        return __('Settings');
    }

    public static function getLabel(): ?string
    {
        return __('FinancialAsset  ');
    }

    public static function getPluralLabel(): ?string
    {
        return __('FinancialAsset  ');
    }
    protected static function getNavigationBadge(): ?string
    {
        return self::getModel()::count(); // TODO: Change the autogenerated stub
    }
}
